import type { NextConfig } from "next";

// Moving to Vercel (2026-08-28, NIFS Dashboard build — see
// docs/superpowers/specs/2026-08-28-nifs-dashboard-v1-design.md) so blog
// publishing and the /dashboard app can run server code (database, auth,
// middleware) instead of the old static-export + cPanel FTP flow. Until the
// Vercel domain cutover actually happens, DO NOT run the old
// `npm run build && node fast-deploy.js` publish flow — it depended on
// `output: "export"` producing an `out/` folder, which no longer happens.
// public/.htaccess is still generated by the build (see package.json) but is
// inert until then — the 200+ legacy-URL redirects it encodes have NOT been
// ported to redirects() below yet. Follow-up work, tracked separately.
const nextConfig: NextConfig = {
  trailingSlash: true,
  images: {
    remotePatterns: [
      // New blog cover/OG images uploaded via the dashboard land here.
      { protocol: "https", hostname: "cirwtkrwzqipuhmqxbwp.supabase.co" },
    ],
  },
};

export default nextConfig;
