import type { NextConfig } from "next";
import blogPosts from "./src/lib/data/blog-posts.json";
import galleryCategories from "./src/lib/data/gallery.json";

// Moving to Vercel (2026-08-28, NIFS Dashboard build — see
// docs/superpowers/specs/2026-08-28-nifs-dashboard-v1-design.md) so blog
// publishing and the /dashboard app can run server code (database, auth,
// middleware) instead of the old static-export + cPanel FTP flow. Until the
// Vercel domain cutover actually happens, DO NOT run the old
// `npm run build && node fast-deploy.js` publish flow — it depended on
// `output: "export"` producing an `out/` folder, which no longer happens.
// public/.htaccess is still generated by the build (see package.json) but is
// now inert on Vercel — redirects() below is the real mechanism there.

const COURSE_SLUGS = [
  "certificate-course-in-fire-safety",
  "diploma-in-fire-safety",
  "diploma-in-health-safety-environment",
  "advanced-diploma-in-fire-safety-adfs",
  "advanced-diploma-in-industrial-safety-adis",
  "pg-diploma-in-fire-safety-pg-dfs",
  "pg-diploma-in-health-safety-environment-pg-dhse",
  "b-sc-in-fire-industrial-safety",
  "b-sc-honours-in-fire-industrial-safety",
  "nebosh-igc",
];

const COURSE_ALIASES: Record<string, string> = {
  "diploma-in-fire-safety-dfs": "diploma-in-fire-safety",
  "certificate-course-in-fire-safety-ccfs": "certificate-course-in-fire-safety",
  "sbtet-certificate-course-in-industrial-safety":
    "certificate-course-in-fire-safety",
  "nebosh-course": "nebosh-igc",
  "nebosh-training": "nebosh-igc",
};

const UTILITY_REDIRECTS: Record<string, string> = {
  "how-to-apply": "/admissions/",
  "job-openings": "/placements/",
  jobs: "/placements/",
  "online-courses": "/courses/",
  "offline-courses": "/courses/",
  "nsdc-courses": "/courses/",
  sbtet: "/courses/",
  "annamalai-university-courses": "/courses/",
  "acharya-nagarjuna-university-courses": "/courses/",
  "mba-in-safety-management": "/courses/",
  "b-sc-in-health-safety-environment": "/courses/",
  "about/mission-vision": "/about/vision-mission/",
  "about/benefits": "/about/company-profile/",
};

const nextConfig: NextConfig = {
  trailingSlash: true,
  images: {
    remotePatterns: [
      // New blog cover/OG images uploaded via the dashboard land here.
      { protocol: "https", hostname: "cirwtkrwzqipuhmqxbwp.supabase.co" },
    ],
  },
  async redirects() {
    return [
      // www -> apex (canonical domain is https://nifsindia.net)
      {
        source: "/:path*",
        has: [{ type: "host", value: "www.nifsindia.net" }],
        destination: "https://nifsindia.net/:path*",
        permanent: true,
      },
      { source: "/homepage.html", destination: "/", permanent: true },

      // Old WordPress blog URLs -> new /blog/<slug>/ pages
      ...blogPosts.map((post: { slug: string }) => ({
        source: `/${post.slug}`,
        destination: `/blog/${post.slug}/`,
        permanent: true,
      })),

      // Old WordPress course URLs -> new /courses/<slug>/ pages
      ...COURSE_SLUGS.map((slug) => ({
        source: `/${slug}`,
        destination: `/courses/${slug}/`,
        permanent: true,
      })),

      // Old course URLs with a different slug suffix
      ...Object.entries(COURSE_ALIASES).map(([oldSlug, newSlug]) => ({
        source: `/${oldSlug}`,
        destination: `/courses/${newSlug}/`,
        permanent: true,
      })),

      // Old gallery category URLs -> new filterable /gallery/ page
      // ("practical-training-yard" has its own real page, so it's excluded
      // to avoid redirecting a page to itself).
      ...galleryCategories
        .filter(
          (cat: { slug: string }) => cat.slug !== "practical-training-yard",
        )
        .map((cat: { slug: string }) => ({
          source:
            cat.slug === "recognition-gallery"
              ? `/${cat.slug}`
              : `/gallery/${cat.slug}`,
          destination: `/gallery/?category=${cat.slug}`,
          permanent: true,
        })),

      // GSC-indexed root-level URL for the practical training yard photos
      {
        source: "/practical-training-yard",
        destination: "/gallery/practical-training-yard/",
        permanent: true,
      },

      // Visakhapatnam has its own dedicated landing page
      {
        source: "/nifs-visakhapatnam",
        destination: "/centers/visakhapatnam/",
        permanent: true,
      },
      {
        source: "/vizag",
        destination: "/centers/visakhapatnam/",
        permanent: true,
      },
      {
        source: "/visakhapatnam",
        destination: "/centers/visakhapatnam/",
        permanent: true,
      },

      // Old per-city landing pages -> the single current /centers/ page.
      // Bounded to the "nifs-" prefix (no real route starts with it) so
      // this can't accidentally shadow an actual page.
      {
        source: "/nifs-:city([a-z-]+)",
        destination: "/centers/",
        permanent: true,
      },

      // High-demand category with no dedicated page -> course catalog
      {
        source: "/category/safety-officer-course",
        destination: "/courses/",
        permanent: true,
      },

      // Old WordPress taxonomy archives -> current blog index
      { source: "/tag/:path*", destination: "/blog/", permanent: true },
      { source: "/category/:path*", destination: "/blog/", permanent: true },

      // Old utility/program pages with no 1:1 page today
      ...Object.entries(UTILITY_REDIRECTS).map(([oldSlug, dest]) => ({
        source: `/${oldSlug}`,
        destination: dest,
        permanent: true,
      })),

      // NOTE: the old .htaccess had one more rule — an unconditional
      // catch-all sending ANY unmatched single-segment path to /blog/.
      // Deliberately NOT ported: Next.js redirects() run before page
      // resolution, so a blanket rule here would redirect every real
      // top-level page (/about, /contact, /courses, ...) to /blog/ too.
      // A handful of very old, untracked URLs not covered by any rule
      // above will 404 instead of soft-redirecting — a real but bounded
      // gap, safer than the alternative.
    ];
  },
};

export default nextConfig;
