import type { NextConfig } from "next";

// Hosted on Jain Infotech's cPanel via static export + FTP (Vercel migration
// was rolled back 2026-08-23 after an HTTPS/DNS outage). Static export can't
// run redirects()/headers() — public/.htaccess (generated by
// scripts/generate-htaccess.js from the same source data) is the source of
// truth for legacy-URL 301s and security headers instead.
const nextConfig: NextConfig = {
  output: "export",
  trailingSlash: true,
  images: { unoptimized: true },
};

export default nextConfig;
